services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  server:
    build: .
    container_name: p2p_tracker
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - redis
    command: ["./p2p_server", "redis", "${REDIS_PORT}", "${THREAD_COUNT}"]